#!/usr/bin/env guile

Test runner for gram. Adapted from Yawar Amin's ggspec runner.
Copyright (c) 2016 J David Smith

!#

(add-to-load-path (string-append (dirname (current-filename)) "/" "lib/"))
(add-to-load-path (string-append (dirname (current-filename)) "/test/support/"))
(add-to-load-path (string-append (dirname (current-filename)) "/test/mocks/"))

(use-modules (gram support test-setup)
             (srfi srfi-64)
             (ice-9 local-eval)
             (ice-9 ftw))

(test-runner-current (tap-runner))

(test-begin "lib")

(let ((specs (scandir "test/lib" (lambda (fname)
                                   (string-suffix? "_spec.scm" fname)))))
  (map-in-order (lambda (spec) (primitive-load (string-append "test/lib/" spec)))
                specs))

(test-end "lib")
